CREATE IF NOT EXIST ROLES(
    id SERIAL,
    nameRole VARCHAR(1OO) NOT NULL
);

CREATE IF NOT EXIST USERS(
    id SERIAL,
    name VARCHAR(1OO) NOT NULL,
    email VARCHAR(1OO) NOT NULL,
    password VARCHAR(1OO) NOT NULL,
    id_roll FOREING KEY ROLES,
);
